### ISSUE TITLE
nas_ab_status

### ISSUE THREAD

**Issue by 103017547** [WAdama/nas_ab_status#1]
Thanks WAdama, the code works perfect. Would this code also be suitable to look at the Synology Hyper Backup status?

thanks,

Gareth

**Comment by WAdama** [comment]
Hi Gareth,

thanks for the appreciation.

I tried something for Hyper Backup, too. But it seems only the cloud backup have a sqlite db file which contains the necessary data. The path to the backup data is /volume1/@img_bkp_cache.

In my case I have there a directory beginning with hidrive according to my backup to Strato HiDrive. The name of the database file is storage_statistics.db, which contains useable data.

I also have backups to Hyper Backup Vault on another Synology. The only directories for them I found beginning with ClientCache_image_image_remote don't contain any database files with usable data.

Kind regards
Ingo

**Comment by 103017547** [comment]
Hi Ingo, yes it seems the hyper backup monitoring is problematic. The only working solution I have found so far is to query the sqlite database of the CMS with powershell script. See https://github.com/Areku95/SynoBackupSensor. This way with powershell has some downside on it as you need to change the account of the PRTGProbeService, to the NAS account. 
Maybe solution for your approach?

regards,

Gareth

**Comment by WAdama** [comment]
Hi Gareth, 
I also know this repository. But i don't use the CMS. It's a little overkill for two Synos in my case.
Kind regards
Ingo
