### ISSUE TITLE
Multiple devices with same name

### ISSUE THREAD

**Issue by pitah81** [WAdama/nas_ab_status#3]
Can this script somehow handle multiple devices that are using the same computer name? Unfortunately many of our customers has a generic AD20xx server name for domain controllers, same goes for RDS20xx. Would it be possible to connect the script to something else than just the name of the server as to work around this?

**Comment by WAdama** [comment]
Hi Peter,

I have to admit I never thought about that kind of constellation. Is ABB accepting double device names?

I will have a look into the database ABB is using. If I remember correct there was also a device id.

Regards
Ingo

**Comment by pitah81** [comment]
Yes, it does allow for server backups with same server name. Else we would have a real nightmare.

I would be very grateful if it would be possible to use a device ID or some other anchor which is unique that each device and disconnected from computer/sever name.

Best regards
Peter

**Comment by WAdama** [comment]
Then I will set this as a feature request...

But it could take a few days...

**Comment by pitah81** [comment]
Thanks!

And it will take whatever time it takes, as you're doing this on your spare time. I would be happy if you got it working whatever time it takes.

**Comment by WAdama** [comment]
One thing puzzles me a little...

If the devices all have the same name, how do you differentiate between them in ABB?

**Comment by pitah81** [comment]
> One thing puzzles me a little...
> 
> If the devices all have the same name, how do you differentiate between them in ABB?

By creating and applying a template for each customer, and connecting a user account for the customer to that template. You'll have to excuse the swedish, but I've included an example from physical server backup view. As you can see they all have the same "Device" name but different "Task" name as that is created from the template. I suppose I could rename the tasks to something like "Customer - Servername" if it would be possible to extract the backup status using task name as anchor.

![AB-distinguish](https://user-images.githubusercontent.com/1994575/109569709-21532d80-7ae9-11eb-87e7-5fb5d7c42816.png)

**Comment by WAdama** [comment]
Then I think the easiest way may to add afilter for the templates.

I will have a look for this...

**Comment by WAdama** [comment]
Hi Peter,

if you feel like doing some testing:
[https://github.com/WAdama/nas_ab_status/tree/Test](url)

Have also a look at the updated documentation...

**Comment by pitah81** [comment]
I just tested it out, and from what I can tell it seems to work as expected. Well done!

**Comment by WAdama** [comment]
Thanks...
Optimistic as I was, I've already moved it to master branch.
Then I will close this...
