### ISSUE TITLE
Warning by lookup value 'Undefined lookup value (0)'

### ISSUE THREAD

**Issue by pitah81** [WAdama/nas_ab_status#5]
Would it be possible to have a check if a running backup is active to avoid getting the Warning by lookup value 'Undefined lookup value (0)' as it returns as it is now?

Also I'm having some trouble with some backups not reporting even though I have double checked the task name and server name, but I'm doing some research into if it could have to do with task name containing Swedish letters like ÅÄÖ.

**Comment by WAdama** [comment]
Hmm, I never had an error during running backup, I have to check for this.
Also I never used special characters as we have in Germany also the "Umlaut" (ÄÖÜäöü). It's for me normal never to use that characters, so I never tested for it.

**Comment by pitah81** [comment]
I can now confirm having 'Umlaut' characters in task name does indeed break the function. However, like you point out it's best to avoid such letters in general when working with shell based interaction. So that solved the errors of it not returning values for backups that aren't running. However if the scripts run while the backup is working in Active Backup for business It seems like it fails for me, could it be that the entry get's locked in sqlite somehow while the task is active?

**Comment by WAdama** [comment]
Hi Peter,

is possible you didn't use the actual lookup file? The actual one has an entry for value 0..

**Comment by WAdama** [comment]
As for the 'Umlaut' have you tested set the names into quotation marks? I just tried that and it worked then.

**Comment by WAdama** [comment]
Hi Peter,
any news? Did you check the points mentioned before?

**Comment by pitah81** [comment]
Of course I missed updating the lookup file. And like you say, it works with 'Umlaut' if I use quotation marks. Thanks again! I owe you many cups of coffee :-)

**Comment by pitah81** [comment]
Of course I missed updating the lookup file. And like you say, it works with 'Umlaut' if I use quotation marks. Thanks again! I owe you many cups/glasses of coffee/tea/beer :-)

**Comment by WAdama** [comment]
Then my world is good again... :-)
I will add a hint for the "Umlaut"...
