### ISSUE TITLE
jq package ?

### ISSUE THREAD

**Issue by MatthieuNoirbusson** [WAdama/nas_ab_status#7]
Hello,

Your code require jq package. How can you install it on a new Synology device ?

Thanks,

Matthieu

**Comment by WAdama** [comment]
Hi Matthieu,

now I'm a little bit puzzled. On my Synos jq is installed by default.
I have to admit, this Syno is updated from 6.24 over 7.0 to 7.1.

On my Synos it's located under /bin.

Regards
Ingo

**Comment by MatthieuNoirbusson** [comment]
You 're right. The problem was not with jq but with this line:

TASKID=$(sqlite3 /volume1/@ActiveBackup/config.db "select task_id from backup_task_device where device_id like '$DEVICEID'")

In my case, this command returns all 4 task IDs I created on my device, not just one.

So I replace it with: TASKID=$(sqlite3 /volume1/@ActiveBackup/config.db "select task_id from task_table where task_name like '$TASK'")

And now it's ok.

Thank you,
Matthieu

**Comment by WAdama** [comment]
Hi Matthieu,

good to hear it's not a missing jq. That would be a pain to get one onto DSM... ;-)

I thought in case of the backups more of one task and several devices.

May I ask why you have several tasks for one device? Maybe I can consider it in my script.

**Comment by MatthieuNoirbusson** [comment]
Hi Ingo,

We always have 2 tasks here: the first one is an incremental backup that is run every day and the second one is a full backup every Sunday. Sometimes we need more jobs when some parts of the file system need specific scheduling.

Best regards,

Matthieu

**Comment by WAdama** [comment]
Do we really speak about Active Backup? As far as I now AB is performing an incremental forever.

So the first backup is a full backup of course and after that it's incremental.

Or is that the file server backup? This is the only task which don't do an image of the device to be backed up.

**Comment by MatthieuNoirbusson** [comment]
In IT production, we like to put on a belt and suspenders.

If the incremental is corrupted, we still have the possibility to start from a not too old full one.

**Comment by WAdama** [comment]
I understand that. I use for my data on NAS Hyper Backup and as fast access Snapshot Replication.

Just for for confirmation: You are speaking about the "File Server" backup, aren't you?

**Comment by MatthieuNoirbusson** [comment]
No it's a server backup.

**Comment by WAdama** [comment]
I ment the variants in ABfB:
"PC"
"Physical Server"
or
"File Server"

**Comment by MatthieuNoirbusson** [comment]
This is "Physical Server"

*Matthieu *

**Comment by WAdama** [comment]
Hmm, then I'm still puzzled because in that mode there is no full or incremental backup, it's incremental forever...

But as your question is answered, I think I can close this...

Regards
Ingo
