### ISSUE TITLE
-sh: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by LdwPet** [WAdama/nas_ab_status#9]
Hello,
When I run the command chmod +x nas_ab_status(_m).sh I get the following error. How can I fix this -sh: syntax error with unexpected token `('

**Comment by WAdama** [comment]
Hi @LdwPet 

Sorry for that, that's just a leftover from the last version, which has two scripts. The writing was ment for both scripts.

Just run "chmod +x nas_ab_status.sh"...

I've also changed the readme.

Regards
Ingo

**Comment by WAdama** [comment]
After two weeks no response: Closing this...
